#!/usr/bin/env bash
# install.sh — Interactive installer for OpenClaw Memory
set -euo pipefail

echo "🧠 OpenClaw Memory — Five-Layer Memory Protection"
echo "======================================================"
echo ""

# Detect workspace
DEFAULT_WORKSPACE="$HOME/clawd"
read -p "Agent workspace directory [$DEFAULT_WORKSPACE]: " WORKSPACE_DIR
WORKSPACE_DIR="${WORKSPACE_DIR:-$DEFAULT_WORKSPACE}"

DEFAULT_OPENCLAW="$HOME/.openclaw"
read -p "OpenClaw data directory [$DEFAULT_OPENCLAW]: " OPENCLAW_DIR
OPENCLAW_DIR="${OPENCLAW_DIR:-$DEFAULT_OPENCLAW}"

# API key (silent input)
read -s -p "OpenRouter API key (or other OpenAI-compatible key): " API_KEY
echo ""

# Model
DEFAULT_MODEL="google/gemini-2.5-flash"
read -p "Observer model [$DEFAULT_MODEL]: " MODEL
MODEL="${MODEL:-$DEFAULT_MODEL}"

echo ""
echo "Installing to: $WORKSPACE_DIR"
echo ""

# Create directories
mkdir -p "$WORKSPACE_DIR/scripts" "$WORKSPACE_DIR/prompts" "$WORKSPACE_DIR/memory" "$WORKSPACE_DIR/logs"

# Copy files
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cp "$SCRIPT_DIR/scripts/"*.sh "$WORKSPACE_DIR/scripts/"
cp "$SCRIPT_DIR/prompts/"*.txt "$WORKSPACE_DIR/prompts/"
chmod +x "$WORKSPACE_DIR/scripts/"*.sh

# Write env config
cat >> "$WORKSPACE_DIR/.env" << EOF

# OpenClaw Memory System
export OPENCLAW_DIR="$OPENCLAW_DIR"
export WORKSPACE_DIR="$WORKSPACE_DIR"
export OPENROUTER_API_KEY="$API_KEY"
export OBSERVER_MODEL="$MODEL"
EOF
chmod 600 "$WORKSPACE_DIR/.env" 2>/dev/null || true

# Create initial observations file
if [ ! -f "$WORKSPACE_DIR/memory/observations.md" ]; then
  echo "# Observations Log" > "$WORKSPACE_DIR/memory/observations.md"
  echo "" >> "$WORKSPACE_DIR/memory/observations.md"
  echo "Auto-generated by Observer agent." >> "$WORKSPACE_DIR/memory/observations.md"
fi

# Platform-specific watcher dependency check (no sudo/package installs)
if [[ "$OSTYPE" == "linux"* ]]; then
  if ! command -v inotifywait &>/dev/null; then
    echo "NOTE: inotifywait not found. Install manually if you want watcher support: inotify-tools"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  if ! command -v fswatch &>/dev/null; then
    echo "NOTE: fswatch not found. Install manually if you want watcher support."
  fi
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "Next steps:"
echo "1. Add the cron job — see config/cron-job.json"
echo "2. Update your openclaw.json — see config/memory-flush.json"
echo "3. Add startup snippets to AGENTS.md — see templates/AGENTS-snippet.md"
echo "   (IMPORTANT: Includes session recovery check)"
echo "4. (Optional) Start the reactive watcher: $WORKSPACE_DIR/scripts/watcher.sh &"
echo ""
echo "Test the observer: $WORKSPACE_DIR/scripts/observer.sh"
